services:
  - type: web
    name: shop-inventory-backend
    env: python
    region: oregon
    plan: free
    # Important: Set the root directory to backend folder
    rootDir: ./backend
    # Build command (optional, Render auto-detects requirements.txt)
    buildCommand: "pip install -r requirements.txt"
    # Start command for FastAPI with uvicorn
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"
    # Environment variables
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        sync: false
      - key: CORS_ORIGINS
        value: "https://shop-inventory-xi.vercel.app,http://localhost:3000,*"
      - key: PORT
        value: "10000"
    # Auto-deploy on push to main branch
    autoDeploy: true
    # Health check endpoint
    healthCheckPath: /api 